project:
  type: website
  output-dir: docs

website:
  title: "Daycare Accessibility in Mecklenburg County"
  description: "Spring 2026 Capstone Project for Master of Urban Spatial Analytics
  Program at the University of Pennslyvania's Weitzman School of Design"
  navbar:
    search: false
    background: "#f8f9fa"
    right:
      - href: index.qmd
        text: Home
      - href: Accessibility_Report.qmd
        text: Report
      - href: Documentation.qmd
        text: Documentation
        

format:
  html:
    theme: lux
    toc: true
    code-fold: true